### ISSUE TITLE
마이페이지 추가 및 수정

### ISSUE THREAD

**Issue by wooodypark** [koview/AOS#129]
## 📄 작업 내용
- 마이페이지의 쓸데없는 코드 또는 수정된 사항들 변경

## ✅ To-Do
- [x] 내 리뷰 좋아요 onClick 이벤트 삭제
- [x] 리뷰 리스트들 좋아요 상태에 따른 글자 색 반영
- [x] 좋아요 상태에 따른 icon도 반영
- [x] 마이페이지, 리뷰 작성, 리뷰상세, 온보딩 marginTop 50dp로 수정
